[package]
name = "endo"
version = "0.1.0"
authors = ["Jonas Jensen <jbj@knef.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15"
crossbeam-channel = "0.4.2"
